import type { RegistryItem } from "../schema";

export const components: RegistryItem[] = [
  {
    id: "button",
    name: "Button",
    kind: "component",
    packageName: "@loomlogic/buttons",
    exportName: "Button",
    description: "Primary action primitive with explicit hierarchy, sizing, disabled, and loading states.",
    kits: ["ll-core", "ll-dynamic"],
    importExample: 'import { Button } from "@loomlogic/buttons";',
    codexPrompt: "Use the approved LoomLogic Button from @loomlogic/buttons. Preserve semantic button behavior, visible focus, loading, and disabled states.",
    lifecycle: { status: "Approved", packageApproved: true, reviewedBy: "LoomLogic" },
    codex: { recommendation: "recommended", promotedToSkill: false, note: "Eligible for skill guidance after a separate promotion review." },
  },
  {
    id: "text-field",
    name: "Text field",
    kind: "component",
    packageName: "@loomlogic/forms",
    exportName: "TextField",
    description: "Label-first text entry with hint, validation, and focus treatment.",
    kits: ["ll-core"],
    importExample: 'import { TextField } from "@loomlogic/forms";',
    codexPrompt: "Use TextField from @loomlogic/forms with a visible label. Supply an error or hint only when it helps the user act.",
    lifecycle: { status: "Candidate", packageApproved: false },
    codex: { recommendation: "not-reviewed", promotedToSkill: false, note: "Package review and Codex recommendation are independent decisions." },
  },
  {
    id: "status-badge",
    name: "Status badge",
    kind: "component",
    packageName: "@loomlogic/data-display",
    exportName: "StatusBadge",
    description: "Compact lifecycle indicator that pairs color with a readable text label.",
    kits: ["ll-core"],
    importExample: 'import { StatusBadge } from "@loomlogic/data-display";',
    codexPrompt: "Use StatusBadge for registry lifecycle only; do not use lifecycle labels as application success or error states.",
    lifecycle: { status: "Approved", packageApproved: true, reviewedBy: "LoomLogic" },
    codex: { recommendation: "recommended", promotedToSkill: false, note: "Awaiting explicit skill promotion." },
  },
  {
    id: "experimental-button",
    name: "Experimental button",
    kind: "component",
    packageName: "@loomlogic/labs",
    exportName: "ExperimentalButton",
    description: "A bounded sandbox for third-party-derived or speculative button treatments.",
    kits: ["ll-dynamic"],
    importExample: 'import { ExperimentalButton } from "@loomlogic/labs";',
    codexPrompt: "Do not use @loomlogic/labs in production unless the application explicitly enables experimental packages.",
    lifecycle: { status: "Experimental", packageApproved: false },
    codex: { recommendation: "withheld", promotedToSkill: false, note: "Experimental work is never recommended by default." },
  },
];
